### ISSUE TITLE
Fix how ois scores are grabbed

### ISSUE THREAD

**Issue by MarcoPellero** [MarcoPellero/oliTracker#7]
Right now if there's an `ois_something` problem and also a `something` problem (without the prefix) or `other_prefix_something` (with ANY prefix), the score associated to the ois problem is the one without the prefix. This prefix shenanigan also affects how links are extrapolated, and they can be wrong

For example for `user=CRICK` and `comp=ois_3` it says that the task `monete` has some points to it, and the link points to the right task, but the user doesn't actually have points on `ois_monete`, they have it on `tai_monete`

**Comment by MarcoPellero** [comment]
UPDATE: this affects OII tasks aswell (predictably...)

For example for `user=eric` and `comp=oii` it shows 2005's messaggi as completed, even though before loading the scores it comes up as unavailable. This is because there's a task called `abc_messaggi`.

It might be ok to look for strictly for `${comp}_${task}` (for example `oii_task` or `ois_task`) but only if the site is always consistent with task name formatting

**Comment by Alenygam** [comment]
> UPDATE: this affects OII tasks aswell (predictably...)
> 
> For example for `user=eric` and `comp=oii` it shows 2005's messaggi as completed, even though before loading the scores it comes up as unavailable. This is because there's a task called `abc_messaggi`.
> 
> It might be ok to look for strictly for `${comp}_${task}` (for example `oii_task` or `ois_task`) but only if the site is always consistent with task name formatting

One way to fix this for oii tasks would be to scrape the id from the task url and then simply strictly comparing it with the user query.
